
name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  
  build:
    runs-on: windows-latest
    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        
      - uses: actions/checkout@v2.3.4
            
      - name: Restore Packages
        run: nuget restore
        
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1.3
        
      - name: Build app for release
        run: msbuild EXILED-DLL-Archiver\EXILED-DLL-Archiver.csproj -t:rebuild -verbosity:diag -property:Configuration=Release
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: EXILED-DLL-Archiver.exe
          path: EXILED-DLL-Archiver/bin/Release/EXILED-DLL-Archiver.exe
